version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:management'
    ports:
      - "5672:5672"
      - "15672:15672"
  messagequeue:
    container_name: app
    build: .
    command: mvn clean spring-boot:run
    ports:
      - "8282:8282"
    depends_on:
      - rabbitmq